version: '3'

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: geraldocoosta/php-eca:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: geraldocoosta/nginx-com-laravel
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - laranet

networks:
  laranet:
    driver: bridge