apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 3
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: geraldocoosta/go-http:v5
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080
        env:
          - name: "NAME"
            valueFrom:
              configMapKeyRef:
                name: goserver-configmap
                key: NAME
          - name: "AGE"
            valueFrom:
              configMapKeyRef:
                name: goserver-configmap
                key: AGE
