apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 3
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: geraldocoosta/go-http:v6
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: goserver-configmap
        volumeMounts:
          - mountPath: "/go-server/myfamily"
            name: config
      volumes:
        - name: config
          configMap:
            name: goserver-configmap-family
            items:
              - key: members
                path: "family.txt"
